* Latest Emacs using Nix (flakes)

Build latest Emacs version from source using Nix.

** Usage

#+begin_src shell
$ nix run github:hraban/emacs-nix
#+end_src

(The first run will take a long time while it builds Emacs from source.)

To install to your system:

#+begin_src shell
# Make sure it actually builds before we go thrashing /Applications
if nix build --no-link github:hraban/emacs-nix; then
    ln -s "$(nix build --no-link --print-out-paths github:hraban/emacs-nix)/Applications/Emacs.app" /Applications/
fi
#+end_src

*** Update

To update to latest Emacs, download this repository, run:

#+begin_src shell
$ nix flake update
#+end_src

... and run your desired command locally:

#+begin_src shell
$ nix run .
# or
$ nix build .
#+end_src

** Why use this?

Only if you want to run the latest Emacs version from source. If you’re fine with an older Emacs, just use =nix-env -i emacs=.

** Install Nix and enable Flakes

First: [[https://nixos.org/download.html][install Nix]] itself.

See the [[https://nixos.wiki/wiki/Flakes#Enable_flakes][instructions to enable flake support]]. If you haven’t enabled them system-wide (or don’t want to), replace every =$ nix ...= above with:

#+begin_src shell
$ nix --experimental-features 'nix-command flakes' ...
#+end_src

** License

Copyright © 2022  Hraban Luyat

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, version 3 of the License.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
