* Latest Emacs using Nix (flakes)

Build latest Emacs version from source using Nix.

This has become my playground for trying various builds of Emacs on Mac from a single easily managable location. Try it locally and see what works for you.

** Usage

#+begin_src shell
$ nix run github:hraban/emacs-nix
#+end_src

(The first run will take a long time while it builds Emacs from source.)

There are three different builds offered by this flake:

- =from-src= (Mac only, default)
- =mac-port= (Mac only)
- =from-nixpkgs= (default on other systems)

*** =from-nixpkgs=

This reuses the derivation from nixpkgs (which is quite complex and full of
special cases), and uses that to build Emacs from its latest git master, instead
of from the version pinned in nixpkgs.

This is the default on non-Mac systems. The only reason to specify this explicitly, is because you’re on Mac, and you want to see what nixpkgs Mac looks like on Mac with the latest version of Mac:

#+begin_src shell
$ nix run github:hraban/emacs-nix#from-nixpkgs
#+end_src

Installation of the nixpkgs build doesn’t support =cp -r= of the resulting app bundle, so you must use:

#+begin_src shell
# Make sure it actually builds before we go thrashing /Applications
if nix build --no-link github:hraban/emacs-nix#from-nixpkgs; then
    ln -s "$(nix build --no-link --print-out-paths github:hraban/emacs-nix#from-nixpkgs)/Applications/Emacs.app" /Applications/
fi
#+end_src

This is suboptimal, to put it mildly. There are many reasons to dislike this solution (which is why I added the other builds, to begin with).

*** =from-src=

This is a manual derivation which just fetches latest git and compiles it with
no patches or special sauce or anything. It uses some mac-specific compiler flags, so I’ve only made this package available on Mac.

Since this is the default on Mac, and it’s not available on any other system, there should never be a need to explicitly specify this package.

To install this system-wide on Mac:

#+begin_src shell
cp -r --preserve=timestamps result/Emacs.app /Applications/
#+end_src

*** =mac-port=

The [[https://nixos.wiki/wiki/Emacs][Nix wiki has a page on Emacs]], with a chapter on building a version using a Mac community overlay with patches from [[https://github.com/d12frosted/homebrew-emacs-plus/][emacs-plus]]. I’ve put it it in a derivation in this flake:

#+begin_src shell
$ nix run github:hraban/emacs-nix#mac-port
#+end_src

It still flickers.

The desperate search continues for a reliable Emacs build on Mac.

** Update

To update to latest Emacs, download this repository, run:

#+begin_src shell
$ nix flake update
#+end_src

... and run your desired command locally:

#+begin_src shell
$ nix run .
# or
$ nix build .
#+end_src

Optionally with any specific package of your choice.

** Why use this?

Only if you want to run the latest Emacs version from source. If you’re fine with an older Emacs, just use =nix-env -i emacs=.

** Install Nix and enable Flakes

First: [[https://nixos.org/download.html][install Nix]] itself.

See the [[https://nixos.wiki/wiki/Flakes#Enable_flakes][instructions to enable flake support]]. If you haven’t enabled them system-wide (or don’t want to), replace every =$ nix ...= above with:

#+begin_src shell
$ nix --experimental-features 'nix-command flakes' ...
#+end_src

** License

Copyright © 2022, 2023  Hraban Luyat

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, version 3 of the License.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
